#!/bin/bash

Escape="\033";
CyanF="${Escape}[36m";
WhiteF="${Escape}[37m";
RedF="${Escape}[31m";
BoldOn="${Escape}[1m";
BoldOff="${Escape}[22m";
Reset="${Escape}[0m";
 
function genData {
  if [ -d "$1/png" ] ; then
    echo "Good... $1/png exists..."
    echo "Generating DataURIs from the images..."
  else
    echo -e "$1/png does not exist, ${RedF}${BoldOn}aborting${BoldOff}${Reset}..."
    exit 1
  fi
  rm $1/b64/*
  data="data:image/png;base64,"
  for f in $1/png/*.png
  do
    ff=$(basename $f)
    data=$(openssl enc -base64 -in $f | tr -d '\n' | sed -e 's/^/data:image\/png;base64,/')
	if [ $DEBUG -eq 1 ]
	then
		echo -e "--Processing ${CyanF}$f${Reset}, outputting to ${CyanF}$1/b64/$ff.b64${Reset}"
	fi
    echo $data > "$1/b64/$ff.b64"
  done
}

function replaceData {
  B=($1)
  color="${B[@]^}"
  file="$1/less/Smooth$color-Images.less"
  cp Common/SmoothColor-Images.less $file
  echo "Creating $file..."
  echo "Including images in $file..."
  cat images.txt | while read -r i
  do
    if grep -q "$i" "$file"
    then
      uri=$(cat $1/b64/$i)
      sed -i s@$i@$uri@g $file > $file.tmp
	  if [ $DEBUG -eq 1 ]
	  then
		echo -e "--Inserting ${CyanF}$i${Reset}"
	  fi
    fi
  done
}

function makeIncludes {
  up="${1^}"
  rm  Common/SmoothColor-Includes.less
  echo "@import \"./$1/less/Smooth$up-Colors\";" > tmpInclude
  echo "@import \"./$1/less/Smooth$up-Images\";" >> tmpInclude
  mv tmpInclude Common/SmoothColor-Includes.less
  echo "Generated Include File..."
}

function buildThisBitch {
  up="${1^}"
  lessc Common/SmoothColor.less $1/css/Smooth$1-uncompressed.css
  NX=$?
  lessc -x Common/SmoothColor.less $1/css/Smooth$1.css
  if [ $? -eq 0 ] && [ $NX -eq 0 ]
  then
	echo "Compile Completed!"
  else
	echo "Compile has failed, exiting with 1"
	exit 1
  fi
}

if [ $# -lt 1 ]
then
  echo "Usage: $0 {color} {debug? optional}"
  echo "Where color is {red,blue,purple}"
  echo "And where debug? is 0 or 1"
fi

if [ $2 ]
then
	if [ $2 -eq 1 ]
	then
		DEBUG=1
	else
		DEBUG=0
	fi
else
	DEBUG=0
fi

if [ $1 ]
then
	genData $1
	replaceData $1
	makeIncludes $1
	buildThisBitch $1
fi
